# Generated by Django 2.2.13 on 2020-07-20 12:23

from django.db import migrations, models
import django.db.models.deletion
import filer.fields.file


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='SvgImage',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='+', serialize=False, to='cms.CMSPlugin')),
                ('label', models.CharField(blank=True, help_text='Optional label for this plugin.', max_length=128, verbose_name='label')),
                ('id_name', models.CharField(blank=True, max_length=50, verbose_name='id name')),
                ('tag_type', models.CharField(blank=True, choices=[('', ''), ('figure', 'figure')], max_length=50, null=True, verbose_name='tag Type')),
                ('additional_class_names', models.TextField(blank=True, help_text='Comma separated list of additional classes to apply to tag_type', verbose_name='additional classes')),
                ('alignment', models.CharField(blank=True, choices=[('left', 'left'), ('right', 'right'), ('center', 'center')], max_length=10, null=True, verbose_name='image alignment')),
                ('width', models.PositiveIntegerField(blank=True, null=True, verbose_name='width')),
                ('height', models.PositiveIntegerField(blank=True, null=True, verbose_name='height')),
                ('caption_text', models.CharField(blank=True, max_length=255, null=True, verbose_name='caption text')),
                ('alt_text', models.CharField(blank=True, max_length=255, null=True, verbose_name='alt text')),
                ('svg_image', filer.fields.file.FilerFileField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='filer.File', verbose_name='file')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
