# Generated by Django 2.2.13 on 2020-07-21 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmsplugin_svg', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='svgimage',
            name='tag_type',
            field=models.CharField(blank=True, choices=[('', ''), ('figure', 'figure')], default='', max_length=50, verbose_name='tag Type'),
        ),
    ]
